config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/tips/', to: 'tips#index'
  get 'tips/new'
  get 'tips/show'
  get '/tips/:id', to: 'tips#show'
  delete '/tips/:id', to: 'tips#destroy'

  get '/sign_in', to: 'sessions#new'
  get '/logout', to: "sessions#destroy"
  post '/sessions/new', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/users/new', to: 'users#new' 
  post '/users', to: 'users#create'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'users/:id/edit', to: 'users#edit'
  patch 'users/:id', to: 'users#update'

  get '/tips/new', to: 'tips#new'
  post '/tips', to: 'tips#create'
  get '/tips/:id', to: 'tips#show', as: 'tip'
  get 'tips/:id/edit', to: 'tips#edit'
  patch '/tips/:id', to: 'tips#update'

  get '/places', to: 'places#index', as: 'place'
  get '/places/:id', to: 'places#show'

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :users
	has_many :tips
end

app/models/tip.rb
class Tip < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
	
	validates :name, presence: true, length: { maximum: 200 }
	validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tips
	belongs_to :place
	
	has_secure_password

	validates :email, uniqueness: true
	
  	def self.confirm(params)
    	@user = User.find_by({email: params[:email]})
    	@user.try(:authenticate, params[:password])
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include SessionsHelper
  before_action :current_user


end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
	end

	def show
		@place = Place.find_by({id: params[:id]})
		@tip = Tip.where(place_id: params[:id])

		# binding.pry
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		render :new
	end

	def create
	    user_params = params.require(:user).permit(:email, :password)
	    @user = User.confirm(user_params)
	    if @user
	      login(@user)
	      redirect_to user_path(@user)
	    else
	      redirect_to "/sign_in"
	    end
  	end

  	def destroy
    	logout
    	redirect_to root_path
 	end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  	before_action :require_login, except: [:index, :show]

  	def index
    	@tips = Tip.all
  	end

  	def new
    	@tip = Tip.new
    	@places = Place.all
  	end

  	def create
	    @tip = Tip.new(tip_params)
	    @tip.user_id = current_user.id
	 
	    placeId = @tip.place_id
    	if @tip.save
      		redirect_to "/places/#{placeId}"
    	else
      		render :new
    	end
  	end

	def show
	    @tip = Tip.find(params[:id])
	    @author_firstname = @tip.user.first_name
	    @author_lastname = @tip.user.last_name
	end

	def edit
		@user = User.find_by({id: params[:id]})
		# @user = current_user
		@tip = Tip.find(params[:id])
	end

	def update
		#TODO: find tip from params & then assign attributes and save
		tip_id = params[:id]
		tip = Tip.find(params[:id])
		#update the tip
		tip.update_attributes(tip_params)
		#redirect to show
		redirect_to "/tips/#{tip_id}"

	end

	def destroy
		# @tip = Tip.find(params[:id])
		Tip.destroy(params[:id])
		redirect_to '/tips'
	end

  	private

  	def tip_params
    	params.require(:tip).permit(:name, :description, :user_id, :place_id)
  	end

  	def require_login
		if !current_user
			redirect_to sign_in_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:show, :new, :create]

	def new
		@user = User.new
	end

	def create
		# binding.pry
		newPlace = Place.find_by(name: user_params[:place_id])
		newPlaceId = newPlace.id
    	newHash = user_params
    	newHash[:place_id] = newPlaceId
    	@user = User.create(newHash) 
    	if @user.save
    		# binding.pry
    		login(@user)
    		redirect_to "/users/#{@user.id}"
   	 	else 
    		redirect_to "/users/new"
    	end
	end

	def show
		@user = User.find_by({id: params[:id]})
		@tip = Tip.where(user_id: params[:id])
	end

	def edit
		@user = User.find_by({id: params[:id]})
		@places = Place.all
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :place_id)
	end

	def require_login
		if !current_user
			redirect_to sign_in_path
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
	    session[:user_id] = user.id
	    @current_user = user
  	end

  	def current_user
	    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  	end

  	def logged_in?
	    if current_user == nil
		    redirect_to "/sign_in"
	    end
  	end

  	def logout
	    @current_user = session[:user_id] = nil
  	end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default container navbar-fixed-top" id="navbar">
	
		<div class="navbar-header">
			<%= link_to "Vagabond", '/', class: "navbar-brand userbtn" %>
		</div>

		<nav class="navbar navbar-right">
			

			<% if current_user %>
				<%= link_to "Profile", user_path(@current_user), class: "nav btn btn-default navbar-btn userbtn" %>
				<%= link_to "Log Out", '/logout', class: "nav btn btn-default navbar-btn userbtn" %>
			<% else %>
				<%= link_to "Sign Up", "users/new", class: "nav btn btn-default navbar-btn userbtn" %>
				<%= link_to "Sign In", '/sign_in', class: "nav btn btn-default navbar-btn userbtn" %>
			<% end %>


			<%= form_tag("/search", method: "get", class: "navbar-form navbar-right" ) do %>
				<%= label_tag(:q, "") %>
				<%= text_field_tag(:q, "Search Places", class: "form-control") %>
				<%= submit_tag("Search", class: "btn btn-default navbar-btn") %>
			<% end %>
		</nav>		
	
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
  <title>Vagabond</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <!--  <link href="app/stylesheets/places.scss" rel="stylesheet"> -->  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Raleway:100" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="http://dundjinni.com/forums/uploads/Bogie/2A5_CompassRose-1_bg.png"/>

  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHLett8djBo62dDXj0EjCimF8Rd6E8cxg"></script>

  <link rel = "stylesheet", href = "/app/assets/stylesheets/places.scss"
  <%= csrf_meta_tags %>
</head>
		<%= render "/layouts/navbar" %>
		<%= yield %>

</html>

app/views/places/index.html.erb
<body id="places">

   
<div id="map-container">
  <div id="map-canvas"></div>
</div>

</body>

app/views/places/show.html.erb
<body id="places">
	<div class="container">
		<h1><%= @place.name %></h1>
		<span>
			Latitude: <%= @place.latitude %>
			Longitude: <%= @place.longitude %>
		</span>
		<button  type="button" class="btn btn-default btn-lg"><a href="/tips/new">Share a tip!</a></button>
		<% @tip.each do |f| %>
			<ul class="myList">
				<li><a href="/tips/<%=f.id%>">Tip: <%= f.name %></a></li>
			</ul>
		<% end %>
	</div>
</body>

app/views/tips/edit.html.erb
<body id="tips">
	<div class="container">
		<h3>Edit your post here </h3>
		<%= form_for @tip, :url => { :action => "update", method: "patch" } do |f| %>
		  <span>
		    <%= f.text_field :name, placeholder: "Title of the post" %> 
		  </span><br><br>
		  <span>
		    <%= f.text_area :description, placeholder: "Enter comments", :cols => "50", :rows => "10" %>
		  </span><br><br>
		  <%= f.submit "Update" %>
		<% end %>
	</div>
</body>

app/views/tips/index.html.erb
<body id="tips">
	<div class="container">
		<h1>ALL THE TIPS!</h1>
		<% @tips.each do |tip| %>
		<a href="/tips/<%= tip.id %>"><%= tip.name %></a><br>
		<% end %>
	</div>
</body>

app/views/tips/new.html.erb
<body id="tips">
	<div class="container">
		<h1>New tip</h1>
		<%= form_for(@tip) do |f| %>
		  	<span>
		    	<%= f.text_field :name, placeholder: "Tip Name" %> 
		  	</span>
		  	<span>
		    	<%= f.text_field :description, placeholder: "Description" %>
		  	</span>
		  	<span>
		  	 	<%= f.collection_select :place_id, @places,:id,:name, prompt: true %>
		  	</span>
		  		<%= f.submit "Share a post!", class: "btn-submit" %>
		<% end %>
	</div>
</body>

app/views/tips/show.html.erb
<body id="tips">
	<div class="container">
		<h1> <%= @author_firstname %>'s Post </h1>
		<h2>Author: <%= @author_firstname %> <%= @author_lastname %> </h2>
		<h2>Title: <%= @tip.name %></h2>
		<h2>Comment: <%= @tip.description %></h2>&nbsp;
		
		<% if @current_user == @tip.user %>
		<a href = "/tips/<%= @tip.id %>/edit"><button>Edit</button></a>
		<br>
		<%= button_to "Delete", {:controller => :tips,
      :action => 'destroy', :id => @tip.id }, :method => :delete,  data: {confirm: "Are you sure?"} %>
		<% end %>
	</div>
</body>

app/views/users/edit.html.erb
<body id="users">
	<div class="container margin">
		<%= form_for @user do |f| %>
		  <span>
		    <%= f.text_field :first_name, placeholder: "First Name" %> 
		  </span>
		  <span>
		    <%= f.text_field :last_name, placeholder: "Last Name" %>
		  </span>
		  <span>
		    <%= f.collection_select :place_id, @places,:id,:name%>
		  </span>
		  <%= f.submit %>
		<% end %>
	</div>
</body>

app/views/users/new.html.erb
<body id="users">
  <div class="login">
    <div class="container">
      <div class="form">

      <h1>Sign up</h1>
        
        <%= form_for(@user) do |f| %>
        <%= f.text_field :first_name, :placeholder => "First name" %>
        <%= f.text_field :last_name, :placeholder => "Last name" %>
        <%= f.email_field :email, :placeholder => "Email" %>
        <%= f.text_field :place_id, :placeholder => "Home Place" %>
        <%= f.password_field :password, :placeholder => "Password" %>
        <%= f.submit "Create an account", class: "btn-submit" %>
      <% end %>
    
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<body id="users">
	<div class="container">
		<div class="img-with-text margin">
			<img src="http://www.mallorcacyclingtours.com/wp-content/uploads/2014/04/blank-profile-hi.png"><br>
			<ul class="list myList" id="first">
				<li class="info">Name: <%= @user.first_name %> <%= @user.last_name %></li>
				<li class="info">Date Joined: <%= @user.created_at %></li>
				<li class="info" data-no-turbolink="true">Current City:<%= link_to @user.place.name, place_path %> </li> 
		 	</ul>
		 	<% if @current_user == @user %>
		 	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href = "/users/<%= @user.id %>/edit"><button>Edit</button></a>
		 	<% end %>
		</div>
		<div class="column">
			<% @tip.each do |f| %>
				<ul class="myList">
					<li><a href="/tips/<%= f.id %>">Tips: <%= f.name %></a></li>
				</ul>
			<% end %>
		</div>
	</div>
</body> 

app/views/welcome/index.html.erb
<body id="home">
<h1 class='center'>Vagabond</h1>
<h2 class='center'>A travel community</h2>
<p>Share tips about your favorite locations around the world.</p>
</body>